### ISSUE TITLE
Small typo on link to USB cable

### ISSUE THREAD

**Issue by grandaspanna** [Kels316/DIY-Air-Purifier#1]
There's just an extraneous character at the end of the link to the Jaycar 12V usb booster cable in the README. Got the 3D printer humming away...

**Comment by Kels316** [comment]
thanks, fixed it :)

**Comment by grandaspanna** [comment]
Awesome. Did some rummaging/ruminating – would something like this be useful for simplifying things? Should be plug in and go.

 

USB->12V (up to 1.5A ish) converter on a single board with micro USB connector and header for FAN. TBH – I don’t know the exact connector used for chassis fans and what the pinouts are, but that’s easy enough to change.

 

Parts cost should be under $20 and I can assemble limited quantities at zero cost, where quantities is a number between 1 and 50. Any more than that and I’d probably throw it to an offshore manufacturer.

 

If it’s not obvious, the board is intended (designed is too strong a word) to sit inside the case and then the USB socket is accessible from the outside.

 

I haven’t really thought about dimensions/shape, but also easily enough sorted.

 

Oh, Nokia 3310 for reference 😉

 

Phil.

**Comment by Kels316** [comment]
I think I’m missing an attachment?

**Comment by grandaspanna** [comment]
Weird. Gimme a few minutes, just grabbing a coffee.

**Comment by grandaspanna** [comment]
Trying again…

**Comment by grandaspanna** [comment]
Ah, looks like attachments don't work via email.
![air filter pcb rendering](https://user-images.githubusercontent.com/54263749/72393832-3a373d00-3788-11ea-9e83-7bcfdf51154a.png)

**Comment by Kels316** [comment]
Ah ok that looks interesting. For this version I’m trying to keep the components to things people can buy over-the-counter or online from local (Aus) suppliers. Definitely interested in another version that’s a bit more advanced for people who want additional features. This could be incorporated into that.

The fans use a 4 pin connector but I’m not sure what the actual name of it is, should be easy enough to find it on digikey or similar

Cheers,

Adam



 <http://www.phasezero.com.au/> 	 	
Adam Kelly <mailto:adam.kelly@phasezero.com.au>
Director | Phase Zero Consulting Services <http://www.phasezero.com.au/>
0400 589 095 | www.phasezero.com.au <tel:+61 400 589 095>

**Comment by grandaspanna** [comment]
Cool. I'll make a couple up for my own purposes. Apart from the PCBs, I source the components from local suppliers when I do my own assembly. Purely for hobby purposes, I sell a few electronic bits on Tindie. Their fees and PayPal fees are a pain, but not aware of too many alternatives.

Got an old board with the same basic layout handy, so I'll test that. Found a local shop that has a twin pack of the Corsair fan and ordered those. The 3D printer yielded fruit overnight, so now on to getting the filter and putting it all together.

**Comment by Kels316** [comment]
love it! Keen to see how the build goes with that board.

**Comment by Kels316** [comment]
I have a slack channel set up for this project too, if you want to join in the discussions.

https://join.slack.com/t/phase-zero-workspace/shared_invite/enQtOTA2MzcxMTAzMzAwLWM1MTZkY2FiNTQ0MWFhZTM2ZDMwN2FjMDcyY2MyZDQxMGQ1MmNiMTNlMGIxYzEzMDE3ODY5NTg5MmExMGEyOWY

Cheers,

Adam

 <http://www.phasezero.com.au/> 	 	
Adam Kelly <mailto:adam.kelly@phasezero.com.au>
Director | Phase Zero Consulting Services <http://www.phasezero.com.au/>
0400 589 095 | www.phasezero.com.au <tel:+61 400 589 095>

**Comment by grandaspanna** [comment]
Pics of this evening's testing. Given me enough confidence to order some bits.
![IMG_2839](https://user-images.githubusercontent.com/54263749/72428561-16084a00-37e2-11ea-9021-24c2591a45f3.jpg)
![IMG_2840](https://user-images.githubusercontent.com/54263749/72428563-16084a00-37e2-11ea-9abf-438e40742e90.jpg)

**Comment by Kels316** [comment]
nice one. If you have a model of the board you can flick me I’ll make a version of the fan housing that has a place to mount it, unless you’re already doing that?

**Comment by grandaspanna** [comment]
See if this works. It's not necessarily final, but based on last night's testing, should work ok.
[air_filter_pcbv2.zip](https://github.com/Kels316/DIY-Air-Purifier/files/4068058/air_filter_pcbv2.zip)

**Comment by Kels316** [comment]
awesome, thanks
