### ISSUE TITLE
This is really cool

### ISSUE THREAD

**Issue by steakscience** [Kels316/DIY-Air-Purifier#9]
This is really cool and really exposes how "simple" air purifiers actually are.

My question is, is there a reason you didn't go with purifiers from Xiaomi, which are around $100 anyway?

**Comment by Kels316** [comment]
I haven’t tested the xiaomi units but they look very small. Thanks for the message! 

Cheers,

Adam 

Sent from my iPhone

m: 0400589095

**Comment by Turophile** [comment]
I'd describe the Xiaomi one I have (2S) as "medium" in size - too large for a table top but not quite big enough to be "furniture".

https://www.xiaomitoday.com/xiaomi-mi-air-purifier-2s-review-small-mighty/


Also note $100 small desktop purifier coming to ALDI: 
https://www.aldi.com.au/en/special-buys/special-buys-sat-1-february/saturday-detail-wk05/ps/p/air-purifier-2/
